### PR TITLE
'Source' class: modification of the visible of private field and method.

### PR DESCRIPTION
**Pull request by frozar**
##### Checklist

- [x] `npm test` passes
- [x] commit message follows commit guidelines

##### Description of change
Change the 'private' keyword to 'protected' keyword. Preserve the limited scope of fields and methods of this class. It gives the possibility to derive this class and customise its behavior in client source code.

### CODE REVIEW

**Comment by lzxue** [comment]
> [Previous ci job failures](https://github.com/antvis/L7/actions/runs/3647801544/jobs/6184387617)
> 
> I just try to rebase onto the current `master` branch, just to check if the errors are reproducible.

the error because for  l7  ie compatibility ,import  supercluster  by  ` import "'supercluster/dist/supercluster`  ,  lead to ts error

**Comment by lzxue** [comment]
> > the error because for l7 ie compatibility ,import supercluster by import "'supercluster/dist/supercluster , lead to ts error
> 
> Thank you for the highlight but I don't know well enough the `l7` history and development to fix this issue from the `lint` job. What can I do about that?
I want kown,What function do you need to expand the source

**Comment by frozar** [comment]
I'm really interested by these modifications:
```
protected originData: any;
protected rawData: any;
```

And if I can have access to all `private` method (so `protected`) in my derived class, I would be really happy :smiley:

**Comment by lzxue** [comment]
> I'm really interested by these modifications:
> 
> ```
> protected originData: any;
> protected rawData: any;
> ```
> 
> And if I can have access to all `private` method (so `protected`) in my derived class, I would be really happy 😃

ok , next version i will this properties to protected

**Comment by lzxue** [comment]
new version already supports

**Pull request closed without merging**
